//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.AspNet.SignalR.Utils {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.AspNet.SignalR.Utils.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized command &apos;{0}&apos;.
        /// </summary>
        internal static string Error_UnrecognizedCommand {
            get {
                return ResourceManager.GetString("Error_UnrecognizedCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly &apos;{0}&apos; could not be loaded because it is a bad image. http://support.microsoft.com/kb/967163.
        /// </summary>
        internal static string Notify_BadImage {
            get {
                return ResourceManager.GetString("Notify_BadImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating temp directory {0}.
        /// </summary>
        internal static string Notify_CreatingTempDirectory {
            get {
                return ResourceManager.GetString("Notify_CreatingTempDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: .
        /// </summary>
        internal static string Notify_Error {
            get {
                return ResourceManager.GetString("Notify_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate HubProxy.
        /// </summary>
        internal static string Notify_GenerateHubProxy {
            get {
                return ResourceManager.GetString("Notify_GenerateHubProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generates HubProxy JavaScript files for server Hub classes..
        /// </summary>
        internal static string Notify_GeneratesHubProxyJSFilesForHub {
            get {
                return ResourceManager.GetString("Notify_GeneratesHubProxyJSFilesForHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usage: signalr &lt;command&gt; [args]
        ///
        ///Available commands:
        ///
        ///  {0}
        ///
        ///For more information, visit http://go.microsoft.com/fwlink/?LinkId=275833.
        /// </summary>
        internal static string Notify_Help {
            get {
                return ResourceManager.GetString("Notify_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing performance counters....
        /// </summary>
        internal static string Notify_InstallingPerformanceCounters {
            get {
                return ResourceManager.GetString("Notify_InstallingPerformanceCounters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install performance counters.
        /// </summary>
        internal static string Notify_InstallPerformanceCounters {
            get {
                return ResourceManager.GetString("Notify_InstallPerformanceCounters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installs SignalR performance counters..
        /// </summary>
        internal static string Notify_InstallSignalRPerformanceCounters {
            get {
                return ResourceManager.GetString("Notify_InstallSignalRPerformanceCounters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance counters installed!.
        /// </summary>
        internal static string Notify_PerformanceCountersInstalled {
            get {
                return ResourceManager.GetString("Notify_PerformanceCountersInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance counters uninstalled!.
        /// </summary>
        internal static string Notify_PerformanceCountersUninstalled {
            get {
                return ResourceManager.GetString("Notify_PerformanceCountersUninstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SignalR Utility Version: {0}.
        /// </summary>
        internal static string Notify_SignalRUtilityVersion {
            get {
                return ResourceManager.GetString("Notify_SignalRUtilityVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try running as admin..
        /// </summary>
        internal static string Notify_TryRunningAsAdmin {
            get {
                return ResourceManager.GetString("Notify_TryRunningAsAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall performance counters.
        /// </summary>
        internal static string Notify_UninstallPerformanceCounters {
            get {
                return ResourceManager.GetString("Notify_UninstallPerformanceCounters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstalls SignalR performance counters..
        /// </summary>
        internal static string Notify_UninstallSignalRPerformanceCounters {
            get {
                return ResourceManager.GetString("Notify_UninstallSignalRPerformanceCounters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: .
        /// </summary>
        internal static string Notify_Warning {
            get {
                return ResourceManager.GetString("Notify_Warning", resourceCulture);
            }
        }
    }
}
