using Windows.ApplicationModel.Resources;

namespace Microsoft.AspNet.SignalR.Client
{
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {
        private static ResourceLoader resourceMan;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static ResourceLoader ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    var temp = new ResourceLoader();
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
		
        /// <summary>
        ///   Looks up a localized string similar to The connection was stopped before it could be started..
        /// </summary>
        internal static string Error_ConnectionCancelled {
            get {
                return ResourceManager.GetString("Error_ConnectionCancelled");
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The connection has not been established..
        /// </summary>
        internal static string Error_ConnectionHasNotBeenEstablished
        {
            get
            {
                return ResourceManager.GetString("Error_ConnectionHasNotBeenEstablished");
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Incompatible protocol version..
        /// </summary>
        internal static string Error_IncompatibleProtocolVersion
        {
            get
            {
                return ResourceManager.GetString("Error_IncompatibleProtocolVersion");
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A HubProxy cannot be added after the connection has been started..
        /// </summary>
        internal static string Error_ProxiesCannotBeAddedConnectionStarted
        {
            get
            {
                return ResourceManager.GetString("Error_ProxiesCannotBeAddedConnectionStarted");
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Server negotiation failed..
        /// </summary>
        internal static string Error_ServerNegotiationFailed
        {
            get
            {
                return ResourceManager.GetString("Error_ServerNegotiationFailed");
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The Start method must be called before data can be sent..
        /// </summary>
        internal static string Error_StartMustBeCalledBeforeDataCanBeSent
        {
            get
            {
                return ResourceManager.GetString("Error_StartMustBeCalledBeforeDataCanBeSent");
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Url cannot contain query string directly. Pass query string values in using available overload..
        /// </summary>
        internal static string Error_UrlCantContainQueryStringDirectly
        {
            get
            {
                return ResourceManager.GetString("Error_UrlCantContainQueryStringDirectly");
            }
        }

    }
}
