trigger:
- master
- release/*
- vsts/*

phases:
- template: ../templates/signalr-build.yml
  parameters:
    queueName: DotNetCore-Windows
    variables:
      SignType: test
      TeamName: AspNetCore
      OfficialBuild: true
      Localize: true
    beforeBuild:
    - task: securedevelopmentteam.vss-secure-development-tools.build-task-policheck.PoliCheck@1
      displayName: 'Run compliance check'
      inputs:
        targetType: F
    - task: ms-vseng.MicroBuildTasks.a0262b21-fb8f-46f8-bb9a-60ed560d4a87.MicroBuildLocalizationPlugin@1
      displayName: 'Install Localization Plugin'
    - task: ms-vseng.MicroBuildTasks.30666190-6959-11e5-9f96-f56098202fef.MicroBuildSigningPlugin@1
      displayName: Install CodeSigning plugin
      inputs:
        signType: $(SignType)
      condition: and(succeeded(), in(variables['SignType'], 'test', 'real'))

    afterBuild:
    - task: ms-vseng.MicroBuildTasks.521a94ea-9e68-468a-8167-6dcf361ea776.MicroBuildCleanup@1
      displayName: Perform Cleanup Tasks
      condition: succeededOrFailed()
